import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { dummyData } from "@/data/dummyData";
// import ApplicationList from "./components/ApplicationTracker/ApplicationList";
// import { Sidebar } from "./components/sidebar";

import prisma from "@/lib/prisma";

export const getServerSideProps = async () => {
   const application = await prisma.Application.findMany();
   console.log({ application });

   return { props: { application } };
};

const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
         >
            {children}
         </body>
      </html>
   );
}
