import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { dummyData } from "@/data/dummyData";
import ApplicationList from "./components/ApplicationTracker/ApplicationList";
import { Sidebar } from "./components/sidebar";

const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
         >
            <section className="grid grid-cols-5 h-full max-h-screen">
               {/* Sidebar */}
               <div className="flex justify-start bg-slate-200 col-span-1 h-full">
                  <Sidebar />
               </div>

               {/* Application List */}
               <div className="col-span-4 max-h-screen overflow-hidden">
                  <div className="h-full overflow-y-auto">
                     <ApplicationList applications={dummyData} />
                  </div>
               </div>
            </section>
            {children}
         </body>
      </html>
   );
}
